graph TD
node1["root<br/>(array)"]
node2["item[0]<br/>(object)"]
node1 --> node2
node3["postId<br/>(number)<br/>1"]
node2 --> node3
node4["id<br/>(number)<br/>1"]
node2 --> node4
node5["name<br/>(string)<br/>id labore ex et quam laborum"]
node2 --> node5
node6["email<br/>(string)<br/>Eliseo@gardner.biz"]
node2 --> node6
node7["body<br/>(string)<br/>laudantium enim quasi est quidem magnam voluptate ..."]
node2 --> node7
node8["item[1]<br/>(object)"]
node1 --> node8
node9["postId<br/>(number)<br/>1"]
node8 --> node9
node10["id<br/>(number)<br/>2"]
node8 --> node10
node11["name<br/>(string)<br/>quo vero reiciendis velit similique earum"]
node8 --> node11
node12["email<br/>(string)<br/>Jayne_Kuhic@sydney.com"]
node8 --> node12
node13["body<br/>(string)<br/>est natus enim nihil est dolore omnis voluptatem n..."]
node8 --> node13
node14["item[2]<br/>(object)"]
node1 --> node14
node15["postId<br/>(number)<br/>1"]
node14 --> node15
node16["id<br/>(number)<br/>3"]
node14 --> node16
node17["name<br/>(string)<br/>odio adipisci rerum aut animi"]
node14 --> node17
node18["email<br/>(string)<br/>Nikita@garfield.biz"]
node14 --> node18
node19["body<br/>(string)<br/>quia molestiae reprehenderit quasi aspernatur aut ..."]
node14 --> node19
node20["item[3]<br/>(object)"]
node1 --> node20
node21["postId<br/>(number)<br/>1"]
node20 --> node21
node22["id<br/>(number)<br/>4"]
node20 --> node22
node23["name<br/>(string)<br/>alias odio sit"]
node20 --> node23
node24["email<br/>(string)<br/>Lew@alysha.tv"]
node20 --> node24
node25["body<br/>(string)<br/>non et atque occaecati deserunt quas accusantium u..."]
node20 --> node25
node26["item[4]<br/>(object)"]
node1 --> node26
node27["postId<br/>(number)<br/>1"]
node26 --> node27
node28["id<br/>(number)<br/>5"]
node26 --> node28
node29["name<br/>(string)<br/>vero eaque aliquid doloribus et culpa"]
node26 --> node29
node30["email<br/>(string)<br/>Hayden@althea.biz"]
node26 --> node30
node31["body<br/>(string)<br/>harum non quasi et ratione tempore iure ex volupta..."]
node26 --> node31